## Fixing data 20-21-22 marzo
Abbiamo fatto troppe prese dati adesso li visualizzo così capisco quali tenere

In [27]:
import pandas as pd
import os
import json
import matplotlib.pyplot as plt
import seaborn as sns
from datetime import datetime, timedelta

In [2]:
dir2003 = "2020.03.20 (chri)"
dir2103 = "2020.03.21"
dir2203 = "2020.03.22 (1)"

Guardo 21 marzo xk quello più incasinato

In [3]:
path = dir2103 + "\\" 
files = os.listdir(path)

In [4]:
list_videos = []
for file in files:
    if file.endswith(".json") :
        with open(path + file, "r") as read_file:
            j_file = json.load(read_file)
            #estraggo solo la data
            
        list_videos.extend(j_file)
len(list_videos)

104151

Mostro tutte le date che ho attraverso un dizionario: strutturate con paese : array(timestamp unici)

In [5]:
dic0321 = {}
for e in list_videos:
    t = e["timestamp"]
    c = e["country_name"]
    if c not in dic0321.keys(): #se non ho già inserito il country
        dic0321[c] = [t]
    else:
        if t not in dic0321[c] : #se non ho già inserito questa data in quel country
            dic0321[c].append(t)
dic0321

{'USA': ['03-20-2020 19:13',
  '03-20-2020 19:44',
  '03-20-2020 20:14',
  '03-20-2020 20:45',
  '03-20-2020 21:15',
  '03-20-2020 21:45',
  '03-20-2020 22:16',
  '03-20-2020 22:46',
  '03-20-2020 23:17',
  '03-20-2020 23:47',
  '03-21-2020 00:18',
  '03-21-2020 00:48',
  '03-21-2020 01:19',
  '03-21-2020 01:49',
  '03-21-2020 02:19',
  '03-21-2020 02:50',
  '03-21-2020 03:20',
  '03-21-2020 03:51',
  '03-21-2020 04:21',
  '03-21-2020 04:52',
  '03-21-2020 05:22',
  '03-21-2020 05:53',
  '03-21-2020 06:23',
  '03-21-2020 06:54',
  '03-21-2020 07:24',
  '03-21-2020 07:55',
  '03-21-2020 08:25',
  '03-21-2020 08:56',
  '03-21-2020 09:26',
  '03-21-2020 09:57',
  '03-21-2020 10:27',
  '03-21-2020 10:58',
  '03-21-2020 11:28',
  '03-21-2020 11:59',
  '03-21-2020 12:29',
  '03-21-2020 13:00',
  '03-21-2020 13:30',
  '03-21-2020 14:01',
  '03-21-2020 14:32',
  '03-21-2020 15:02',
  '03-21-2020 15:33',
  '03-21-2020 16:03',
  '03-21-2020 16:34',
  '03-21-2020 17:04',
  '03-21-2020 17:34',
  '03-21-2020 18:05',
  '03-21-2020 18:35'],
 'Regno Unito': ['03-21-2020 00:13',
  '03-21-2020 00:44',
  '03-21-2020 01:14',
  '03-21-2020 01:45',
  '03-21-2020 02:15',
  '03-21-2020 02:45',
  '03-21-2020 03:16',
  '03-21-2020 03:46',
  '03-21-2020 04:17',
  '03-21-2020 04:47',
  '03-21-2020 05:18',
  '03-21-2020 05:48',
  '03-21-2020 06:19',
  '03-21-2020 06:49',
  '03-21-2020 07:19',
  '03-21-2020 07:50',
  '03-21-2020 08:20',
  '03-21-2020 08:51',
  '03-21-2020 09:21',
  '03-21-2020 09:52',
  '03-21-2020 10:22',
  '03-21-2020 10:53',
  '03-21-2020 11:23',
  '03-21-2020 11:54',
  '03-21-2020 12:24',
  '03-21-2020 12:55',
  '03-21-2020 13:25',
  '03-21-2020 13:56',
  '03-21-2020 14:26',
  '03-21-2020 14:57',
  '03-21-2020 15:27',
  '03-21-2020 15:58',
  '03-21-2020 16:28',
  '03-21-2020 16:59',
  '03-21-2020 17:29',
  '03-21-2020 18:00',
  '03-21-2020 18:30',
  '03-21-2020 19:01',
  '03-21-2020 19:32',
  '03-21-2020 20:02',
  '03-21-2020 20:33',
  '03-21-2020 21:03',
  '03-21-2020 21:34',
  '03-21-2020 22:04',
  '03-21-2020 22:34',
  '03-21-2020 23:05',
  '03-21-2020 23:35'],
 'India': ['03-21-2020 05:13',
  '03-21-2020 05:44',
  '03-21-2020 06:14',
  '03-21-2020 06:45',
  '03-21-2020 07:15',
  '03-21-2020 07:45',
  '03-21-2020 08:16',
  '03-21-2020 08:46',
  '03-21-2020 09:17',
  '03-21-2020 09:47',
  '03-21-2020 10:18',
  '03-21-2020 10:48',
  '03-21-2020 11:19',
  '03-21-2020 11:49',
  '03-21-2020 12:19',
  '03-21-2020 12:50',
  '03-21-2020 13:20',
  '03-21-2020 13:51',
  '03-21-2020 14:21',
  '03-21-2020 14:52',
  '03-21-2020 15:22',
  '03-21-2020 15:53',
  '03-21-2020 16:23',
  '03-21-2020 16:54',
  '03-21-2020 17:24',
  '03-21-2020 17:55',
  '03-21-2020 18:25',
  '03-21-2020 18:56',
  '03-21-2020 19:26',
  '03-21-2020 19:57',
  '03-21-2020 20:27',
  '03-21-2020 20:58',
  '03-21-2020 21:28',
  '03-21-2020 21:59',
  '03-21-2020 22:29',
  '03-21-2020 23:00',
  '03-21-2020 23:30',
  '03-22-2020 00:01',
  '03-22-2020 00:32',
  '03-22-2020 01:02',
  '03-22-2020 01:33',
  '03-22-2020 02:03',
  '03-22-2020 02:34',
  '03-22-2020 03:04',
  '03-22-2020 03:34',
  '03-22-2020 04:05',
  '03-22-2020 04:35'],
 'Germania': ['03-21-2020 01:13',
  '03-21-2020 01:44',
  '03-21-2020 02:14',
  '03-21-2020 02:45',
  '03-21-2020 03:15',
  '03-21-2020 03:45',
  '03-21-2020 04:16',
  '03-21-2020 04:46',
  '03-21-2020 05:17',
  '03-21-2020 05:47',
  '03-21-2020 06:18',
  '03-21-2020 06:48',
  '03-21-2020 07:19',
  '03-21-2020 07:49',
  '03-21-2020 08:19',
  '03-21-2020 08:50',
  '03-21-2020 09:20',
  '03-21-2020 09:51',
  '03-21-2020 10:21',
  '03-21-2020 10:52',
  '03-21-2020 11:22',
  '03-21-2020 11:53',
  '03-21-2020 12:23',
  '03-21-2020 12:54',
  '03-21-2020 13:24',
  '03-21-2020 13:55',
  '03-21-2020 14:25',
  '03-21-2020 14:56',
  '03-21-2020 15:26',
  '03-21-2020 15:57',
  '03-21-2020 16:27',
  '03-21-2020 16:58',
  '03-21-2020 17:28',
  '03-21-2020 17:59',
  '03-21-2020 18:29',
  '03-21-2020 19:00',
  '03-21-2020 19:30',
  '03-21-2020 20:01',
  '03-21-2020 20:32',
  '03-21-2020 21:02',
  '03-21-2020 21:33',
  '03-21-2020 22:03',
  '03-21-2020 22:34',
  '03-21-2020 23:04',
  '03-21-2020 23:34',
  '03-22-2020 00:05',
  '03-22-2020 00:35'],
 'Canada': ['03-20-2020 19:13',
  '03-20-2020 19:44',
  '03-20-2020 20:14',
  '03-20-2020 20:45',
  '03-20-2020 21:15',
  '03-20-2020 21:45',
  '03-20-2020 22:16',
  '03-20-2020 22:46',
  '03-20-2020 23:17',
  '03-20-2020 23:47',
  '03-21-2020 00:18',
  '03-21-2020 00:48',
  '03-21-2020 01:19',
  '03-21-2020 01:49',
  '03-21-2020 02:19',
  '03-21-2020 02:50',
  '03-21-2020 03:20',
  '03-21-2020 03:51',
  '03-21-2020 04:21',
  '03-21-2020 04:52',
  '03-21-2020 05:22',
  '03-21-2020 05:53',
  '03-21-2020 06:23',
  '03-21-2020 06:54',
  '03-21-2020 07:24',
  '03-21-2020 07:55',
  '03-21-2020 08:25',
  '03-21-2020 08:56',
  '03-21-2020 09:26',
  '03-21-2020 09:57',
  '03-21-2020 10:27',
  '03-21-2020 10:58',
  '03-21-2020 11:28',
  '03-21-2020 11:59',
  '03-21-2020 12:29',
  '03-21-2020 13:00',
  '03-21-2020 13:30',
  '03-21-2020 14:01',
  '03-21-2020 14:32',
  '03-21-2020 15:02',
  '03-21-2020 15:33',
  '03-21-2020 16:03',
  '03-21-2020 16:34',
  '03-21-2020 17:04',
  '03-21-2020 17:34',
  '03-21-2020 18:05',
  '03-21-2020 18:35'],
 'Francia': ['03-21-2020 01:13',
  '03-21-2020 01:44',
  '03-21-2020 02:14',
  '03-21-2020 02:45',
  '03-21-2020 03:15',
  '03-21-2020 03:45',
  '03-21-2020 04:16',
  '03-21-2020 04:46',
  '03-21-2020 05:17',
  '03-21-2020 05:47',
  '03-21-2020 06:18',
  '03-21-2020 06:48',
  '03-21-2020 07:19',
  '03-21-2020 07:49',
  '03-21-2020 08:19',
  '03-21-2020 08:50',
  '03-21-2020 09:20',
  '03-21-2020 09:51',
  '03-21-2020 10:21',
  '03-21-2020 10:52',
  '03-21-2020 11:22',
  '03-21-2020 11:53',
  '03-21-2020 12:23',
  '03-21-2020 12:54',
  '03-21-2020 13:24',
  '03-21-2020 13:55',
  '03-21-2020 14:25',
  '03-21-2020 14:56',
  '03-21-2020 15:26',
  '03-21-2020 15:57',
  '03-21-2020 16:27',
  '03-21-2020 16:58',
  '03-21-2020 17:28',
  '03-21-2020 17:59',
  '03-21-2020 18:29',
  '03-21-2020 19:00',
  '03-21-2020 19:30',
  '03-21-2020 20:01',
  '03-21-2020 20:32',
  '03-21-2020 21:02',
  '03-21-2020 21:33',
  '03-21-2020 22:03',
  '03-21-2020 22:34',
  '03-21-2020 23:04',
  '03-21-2020 23:34',
  '03-22-2020 00:05',
  '03-22-2020 00:35'],
 'Corea del sud': ['03-21-2020 09:13',
  '03-21-2020 09:44',
  '03-21-2020 10:14',
  '03-21-2020 10:45',
  '03-21-2020 11:15',
  '03-21-2020 11:45',
  '03-21-2020 12:16',
  '03-21-2020 12:46',
  '03-21-2020 13:17',
  '03-21-2020 13:47',
  '03-21-2020 14:18',
  '03-21-2020 14:48',
  '03-21-2020 15:19',
  '03-21-2020 15:49',
  '03-21-2020 16:19',
  '03-21-2020 16:50',
  '03-21-2020 17:20',
  '03-21-2020 17:51',
  '03-21-2020 18:21',
  '03-21-2020 18:52',
  '03-21-2020 19:22',
  '03-21-2020 19:53',
  '03-21-2020 20:23',
  '03-21-2020 20:54',
  '03-21-2020 21:24',
  '03-21-2020 21:55',
  '03-21-2020 22:25',
  '03-21-2020 22:56',
  '03-21-2020 23:26',
  '03-21-2020 23:57',
  '03-22-2020 00:27',
  '03-22-2020 00:58',
  '03-22-2020 01:28',
  '03-22-2020 01:59',
  '03-22-2020 02:29',
  '03-22-2020 03:00',
  '03-22-2020 03:30',
  '03-22-2020 04:01',
  '03-22-2020 04:32',
  '03-22-2020 05:02',
  '03-22-2020 05:33',
  '03-22-2020 06:03',
  '03-22-2020 06:34',
  '03-22-2020 07:04',
  '03-22-2020 07:34',
  '03-22-2020 08:05',
  '03-22-2020 08:35'],
 'Russia': ['03-21-2020 03:13',
  '03-21-2020 03:44',
  '03-21-2020 04:14',
  '03-21-2020 04:45',
  '03-21-2020 05:15',
  '03-21-2020 05:45',
  '03-21-2020 06:16',
  '03-21-2020 06:46',
  '03-21-2020 07:17',
  '03-21-2020 07:47',
  '03-21-2020 08:18',
  '03-21-2020 08:48',
  '03-21-2020 09:19',
  '03-21-2020 09:49',
  '03-21-2020 10:19',
  '03-21-2020 10:50',
  '03-21-2020 11:20',
  '03-21-2020 11:51',
  '03-21-2020 12:21',
  '03-21-2020 12:52',
  '03-21-2020 13:22',
  '03-21-2020 13:53',
  '03-21-2020 14:23',
  '03-21-2020 14:54',
  '03-21-2020 15:24',
  '03-21-2020 15:55',
  '03-21-2020 16:25',
  '03-21-2020 16:56',
  '03-21-2020 17:26',
  '03-21-2020 17:57',
  '03-21-2020 18:27',
  '03-21-2020 18:58',
  '03-21-2020 19:28',
  '03-21-2020 19:59',
  '03-21-2020 20:29',
  '03-21-2020 21:00',
  '03-21-2020 21:30',
  '03-21-2020 22:01',
  '03-21-2020 22:32',
  '03-21-2020 23:02',
  '03-21-2020 23:33',
  '03-22-2020 00:03',
  '03-22-2020 00:34',
  '03-22-2020 01:04',
  '03-22-2020 01:34',
  '03-22-2020 02:05',
  '03-22-2020 02:35'],
 'Giappone': ['03-21-2020 09:13',
  '03-21-2020 09:44',
  '03-21-2020 10:14',
  '03-21-2020 10:45',
  '03-21-2020 11:15',
  '03-21-2020 11:45',
  '03-21-2020 12:16',
  '03-21-2020 12:46',
  '03-21-2020 13:17',
  '03-21-2020 13:47',
  '03-21-2020 14:18',
  '03-21-2020 14:48',
  '03-21-2020 15:19',
  '03-21-2020 15:49',
  '03-21-2020 16:19',
  '03-21-2020 16:50',
  '03-21-2020 17:20',
  '03-21-2020 17:51',
  '03-21-2020 18:21',
  '03-21-2020 18:52',
  '03-21-2020 19:22',
  '03-21-2020 19:53',
  '03-21-2020 20:23',
  '03-21-2020 20:54',
  '03-21-2020 21:24',
  '03-21-2020 21:55',
  '03-21-2020 22:25',
  '03-21-2020 22:56',
  '03-21-2020 23:26',
  '03-21-2020 23:57',
  '03-22-2020 00:27',
  '03-22-2020 00:58',
  '03-22-2020 01:28',
  '03-22-2020 01:59',
  '03-22-2020 02:29',
  '03-22-2020 03:00',
  '03-22-2020 03:30',
  '03-22-2020 04:01',
  '03-22-2020 04:32',
  '03-22-2020 05:02',
  '03-22-2020 05:33',
  '03-22-2020 06:03',
  '03-22-2020 06:34',
  '03-22-2020 07:04',
  '03-22-2020 07:34',
  '03-22-2020 08:05',
  '03-22-2020 08:35'],
 'Brasile': ['03-20-2020 21:13',
  '03-20-2020 21:44',
  '03-20-2020 22:14',
  '03-20-2020 22:45',
  '03-20-2020 23:15',
  '03-20-2020 23:45',
  '03-21-2020 00:16',
  '03-21-2020 00:46',
  '03-21-2020 01:17',
  '03-21-2020 01:47',
  '03-21-2020 02:18',
  '03-21-2020 02:48',
  '03-21-2020 03:19',
  '03-21-2020 03:49',
  '03-21-2020 04:19',
  '03-21-2020 04:50',
  '03-21-2020 05:20',
  '03-21-2020 05:51',
  '03-21-2020 06:21',
  '03-21-2020 06:52',
  '03-21-2020 07:22',
  '03-21-2020 07:53',
  '03-21-2020 08:23',
  '03-21-2020 08:54',
  '03-21-2020 09:24',
  '03-21-2020 09:55',
  '03-21-2020 10:25',
  '03-21-2020 10:56',
  '03-21-2020 11:26',
  '03-21-2020 11:57',
  '03-21-2020 12:27',
  '03-21-2020 12:58',
  '03-21-2020 13:28',
  '03-21-2020 13:59',
  '03-21-2020 14:29',
  '03-21-2020 15:00',
  '03-21-2020 15:30',
  '03-21-2020 16:01',
  '03-21-2020 16:32',
  '03-21-2020 17:02',
  '03-21-2020 17:33',
  '03-21-2020 18:03',
  '03-21-2020 18:34',
  '03-21-2020 19:04',
  '03-21-2020 19:34',
  '03-21-2020 20:05',
  '03-21-2020 20:35'],
 'Messico': ['03-20-2020 18:13',
  '03-20-2020 18:44',
  '03-20-2020 19:14',
  '03-20-2020 19:45',
  '03-20-2020 20:15',
  '03-20-2020 20:45',
  '03-20-2020 21:16',
  '03-20-2020 21:46',
  '03-20-2020 22:17',
  '03-20-2020 22:47',
  '03-20-2020 23:18',
  '03-20-2020 23:48',
  '03-21-2020 00:19',
  '03-21-2020 00:49',
  '03-21-2020 01:19',
  '03-21-2020 01:50',
  '03-21-2020 02:20',
  '03-21-2020 02:51',
  '03-21-2020 03:21',
  '03-21-2020 03:52',
  '03-21-2020 04:22',
  '03-21-2020 04:53',
  '03-21-2020 05:23',
  '03-21-2020 05:54',
  '03-21-2020 06:24',
  '03-21-2020 06:55',
  '03-21-2020 07:25',
  '03-21-2020 07:56',
  '03-21-2020 08:26',
  '03-21-2020 08:57',
  '03-21-2020 09:27',
  '03-21-2020 09:58',
  '03-21-2020 10:28',
  '03-21-2020 10:59',
  '03-21-2020 11:29',
  '03-21-2020 12:00',
  '03-21-2020 12:30',
  '03-21-2020 13:01',
  '03-21-2020 13:32',
  '03-21-2020 14:02',
  '03-21-2020 14:33',
  '03-21-2020 15:03',
  '03-21-2020 15:34',
  '03-21-2020 16:04',
  '03-21-2020 16:34',
  '03-21-2020 17:05',
  '03-21-2020 17:35'],
 'Italia': ['03-21-2020 01:13',
  '03-21-2020 01:44',
  '03-21-2020 02:14',
  '03-21-2020 02:45',
  '03-21-2020 03:15',
  '03-21-2020 03:45',
  '03-21-2020 04:16',
  '03-21-2020 04:46',
  '03-21-2020 05:17',
  '03-21-2020 05:47',
  '03-21-2020 06:18',
  '03-21-2020 06:48',
  '03-21-2020 07:19',
  '03-21-2020 07:49',
  '03-21-2020 08:19',
  '03-21-2020 08:50',
  '03-21-2020 09:20',
  '03-21-2020 09:51',
  '03-21-2020 10:21',
  '03-21-2020 10:52',
  '03-21-2020 11:22',
  '03-21-2020 11:53',
  '03-21-2020 12:23',
  '03-21-2020 12:54',
  '03-21-2020 13:24',
  '03-21-2020 13:55',
  '03-21-2020 14:25',
  '03-21-2020 14:56',
  '03-21-2020 15:26',
  '03-21-2020 15:57',
  '03-21-2020 16:27',
  '03-21-2020 16:58',
  '03-21-2020 17:28',
  '03-21-2020 17:59',
  '03-21-2020 18:29',
  '03-21-2020 19:00',
  '03-21-2020 19:30',
  '03-21-2020 20:01',
  '03-21-2020 20:32',
  '03-21-2020 21:02',
  '03-21-2020 21:33',
  '03-21-2020 22:03',
  '03-21-2020 22:34',
  '03-21-2020 23:04',
  '03-21-2020 23:34',
  '03-22-2020 00:05',
  '03-22-2020 00:35']}

**Idea**: estraggo dal json generale solo i documenti che presentano quel paese a quei determinati timestamp che abbiamo deciso (basandomi su UK come greenwich)

In [6]:
dic0321.keys()

dict_keys(['USA', 'Regno Unito', 'India', 'Germania', 'Canada', 'Francia', 'Corea del sud', 'Russia', 'Giappone', 'Brasile', 'Messico', 'Italia'])

Bisogna decidere quali date tenere x ogni paese: valutare in base ai fusi orari se no si incasinano con le altre prese dati

Intanto visualizzo le altre date

**20 marzo**

In [176]:
path = dir2003 + "\\" 
files = os.listdir(path)
list_videos = []
for file in files:
    if file.endswith(".json") :
        with open(path + file, "r") as read_file:
            j_file = json.load(read_file)
            
        list_videos.extend(j_file)

In [177]:
dic0320 = {}
for e in list_videos:
    t = e["timestamp"]
    c = e["country_name"]
    if c not in dic0320.keys(): #se non ho già inserito il country
        dic0320[c] = [t]
    else:
        if t not in dic0320[c] : #se non ho già inserito questa data in quel country
            dic0320[c].append(t)
dic0321

{'USA': ['03-20-2020 23:17',
  '03-21-2020 05:22',
  '03-21-2020 11:28',
  '03-21-2020 17:34'],
 'Regno Unito': ['03-21-2020 04:17',
  '03-21-2020 10:22',
  '03-21-2020 16:28',
  '03-21-2020 22:34'],
 'India': ['03-21-2020 09:17',
  '03-21-2020 15:22',
  '03-21-2020 21:28',
  '03-22-2020 03:34'],
 'Germania': ['03-21-2020 05:17',
  '03-21-2020 11:22',
  '03-21-2020 17:28',
  '03-21-2020 23:34'],
 'Canada': ['03-20-2020 23:17',
  '03-21-2020 05:22',
  '03-21-2020 11:28',
  '03-21-2020 17:34'],
 'Francia': ['03-21-2020 05:17',
  '03-21-2020 11:22',
  '03-21-2020 17:28',
  '03-21-2020 23:34'],
 'Corea del sud': ['03-21-2020 13:17',
  '03-21-2020 19:22',
  '03-22-2020 01:28',
  '03-22-2020 07:34'],
 'Russia': ['03-21-2020 07:17',
  '03-21-2020 13:22',
  '03-21-2020 19:28',
  '03-22-2020 01:34'],
 'Giappone': ['03-21-2020 13:17',
  '03-21-2020 19:22',
  '03-22-2020 01:28',
  '03-22-2020 07:34'],
 'Brasile': ['03-21-2020 01:17',
  '03-21-2020 07:22',
  '03-21-2020 13:28',
  '03-21-2020 19:34'],
 'Messico': ['03-20-2020 22:17',
  '03-21-2020 04:22',
  '03-21-2020 10:28',
  '03-21-2020 16:34'],
 'Italia': ['03-21-2020 05:17',
  '03-21-2020 11:22',
  '03-21-2020 17:28',
  '03-21-2020 23:34']}

Anche nel 2020.03.20 c'è il problema

Valuto **22 marzo**

In [9]:
path = dir2203 + "\\" 
files = os.listdir(path)
list_videos = []
for file in files:
    if file.endswith(".json") :
        with open(path + file, "r") as read_file:
            j_file = json.load(read_file)
            #estraggo solo la data
            
        list_videos.extend(j_file)

In [11]:
dic0322 = {}
for e in list_videos:
    t = e["timestamp"]
    c = e["country_name"]
    if c not in dic0322.keys(): #se non ho già inserito il country
        dic0322[c] = [t]
    else:
        if t not in dic0322[c] : #se non ho già inserito questa data in quel country
            dic0322[c].append(t)
dic0322

{'USA': ['03-22-2020 05:28',
  '03-22-2020 11:28',
  '03-22-2020 17:29',
  '03-21-2020 19:06',
  '03-21-2020 19:36',
  '03-21-2020 20:07',
  '03-21-2020 20:37',
  '03-21-2020 21:07',
  '03-21-2020 21:38',
  '03-21-2020 22:08',
  '03-21-2020 22:39',
  '03-21-2020 23:09',
  '03-21-2020 23:40',
  '03-22-2020 00:10'],
 'Regno Unito': ['03-22-2020 10:28',
  '03-22-2020 16:28',
  '03-22-2020 22:29',
  '03-22-2020 00:06',
  '03-22-2020 00:36',
  '03-22-2020 01:07',
  '03-22-2020 01:37',
  '03-22-2020 02:07',
  '03-22-2020 02:38',
  '03-22-2020 03:08',
  '03-22-2020 03:39',
  '03-22-2020 04:09',
  '03-22-2020 04:40',
  '03-22-2020 05:10'],
 'India': ['03-22-2020 15:28',
  '03-22-2020 21:28',
  '03-23-2020 03:29',
  '03-22-2020 05:06',
  '03-22-2020 05:36',
  '03-22-2020 06:07',
  '03-22-2020 06:37',
  '03-22-2020 07:07',
  '03-22-2020 07:38',
  '03-22-2020 08:08',
  '03-22-2020 08:39',
  '03-22-2020 09:09',
  '03-22-2020 09:40'],
 'Germania': ['03-22-2020 11:28',
  '03-22-2020 17:28',
  '03-22-2020 23:29',
  '03-22-2020 01:06',
  '03-22-2020 01:36',
  '03-22-2020 02:07',
  '03-22-2020 02:37',
  '03-22-2020 03:07',
  '03-22-2020 03:38',
  '03-22-2020 04:08',
  '03-22-2020 04:39',
  '03-22-2020 05:09',
  '03-22-2020 05:40'],
 'Canada': ['03-22-2020 05:28',
  '03-22-2020 11:28',
  '03-22-2020 17:29',
  '03-21-2020 19:06',
  '03-21-2020 19:36',
  '03-21-2020 20:07',
  '03-21-2020 20:37',
  '03-21-2020 21:07',
  '03-21-2020 21:38',
  '03-21-2020 22:08',
  '03-21-2020 22:39',
  '03-21-2020 23:09',
  '03-21-2020 23:40'],
 'Francia': ['03-22-2020 11:28',
  '03-22-2020 17:28',
  '03-22-2020 23:29',
  '03-22-2020 01:06',
  '03-22-2020 01:36',
  '03-22-2020 02:07',
  '03-22-2020 02:37',
  '03-22-2020 03:07',
  '03-22-2020 03:38',
  '03-22-2020 04:08',
  '03-22-2020 04:39',
  '03-22-2020 05:09',
  '03-22-2020 05:40'],
 'Corea del sud': ['03-22-2020 19:28',
  '03-23-2020 01:28',
  '03-23-2020 07:29',
  '03-22-2020 09:06',
  '03-22-2020 09:36',
  '03-22-2020 10:07',
  '03-22-2020 10:37',
  '03-22-2020 11:07',
  '03-22-2020 11:38',
  '03-22-2020 12:08',
  '03-22-2020 12:39',
  '03-22-2020 13:09',
  '03-22-2020 13:40'],
 'Russia': ['03-22-2020 13:28',
  '03-22-2020 19:28',
  '03-23-2020 01:29',
  '03-22-2020 03:06',
  '03-22-2020 03:36',
  '03-22-2020 04:07',
  '03-22-2020 04:37',
  '03-22-2020 05:07',
  '03-22-2020 05:38',
  '03-22-2020 06:08',
  '03-22-2020 06:39',
  '03-22-2020 07:09',
  '03-22-2020 07:40'],
 'Giappone': ['03-22-2020 19:28',
  '03-23-2020 01:28',
  '03-23-2020 07:29',
  '03-22-2020 09:06',
  '03-22-2020 09:36',
  '03-22-2020 10:07',
  '03-22-2020 10:37',
  '03-22-2020 11:07',
  '03-22-2020 11:38',
  '03-22-2020 12:08',
  '03-22-2020 12:39',
  '03-22-2020 13:09',
  '03-22-2020 13:40'],
 'Brasile': ['03-22-2020 07:28',
  '03-22-2020 13:28',
  '03-22-2020 19:29',
  '03-21-2020 21:06',
  '03-21-2020 21:36',
  '03-21-2020 22:07',
  '03-21-2020 22:37',
  '03-21-2020 23:07',
  '03-21-2020 23:38',
  '03-22-2020 00:08',
  '03-22-2020 00:39',
  '03-22-2020 01:09',
  '03-22-2020 01:40'],
 'Messico': ['03-22-2020 04:28',
  '03-22-2020 10:28',
  '03-22-2020 16:29',
  '03-21-2020 18:06',
  '03-21-2020 18:36',
  '03-21-2020 19:07',
  '03-21-2020 19:37',
  '03-21-2020 20:07',
  '03-21-2020 20:38',
  '03-21-2020 21:08',
  '03-21-2020 21:39',
  '03-21-2020 22:09',
  '03-21-2020 22:40'],
 'Italia': ['03-22-2020 11:28',
  '03-22-2020 17:28',
  '03-22-2020 23:29',
  '03-22-2020 01:06',
  '03-22-2020 01:36',
  '03-22-2020 02:07',
  '03-22-2020 02:37',
  '03-22-2020 03:07',
  '03-22-2020 03:38',
  '03-22-2020 04:08',
  '03-22-2020 04:39',
  '03-22-2020 05:09',
  '03-22-2020 05:40']}

qua dalla mezzanotte sembra esserci qualche problema

In [12]:
with open("country_names.json") as file:
        country = json.load(file)
country

{'US': {'name': 'USA', 'GMT': -5},
 'GB': {'name': 'Regno Unito', 'GMT': 0},
 'IN': {'name': 'India', 'GMT': 5},
 'DE': {'name': 'Germania', 'GMT': 1},
 'CA': {'name': 'Canada', 'GMT': -5},
 'FR': {'name': 'Francia', 'GMT': 1},
 'KR': {'name': 'Corea del sud', 'GMT': 9},
 'RU': {'name': 'Russia', 'GMT': 3},
 'JP': {'name': 'Giappone', 'GMT': 9},
 'BR': {'name': 'Brasile', 'GMT': -3},
 'MX': {'name': 'Messico', 'GMT': -6},
 'IT': {'name': 'Italia', 'GMT': 1}}

Allora gli orari da estrarre sono circa (per Greenwich - Regno Unito):

per dic0321
- "03-21-2020 04:17"
- "03-21-2020 10:22"
- "03-21-2020 16:28"
- "03-21-2020 22:34"

In [21]:
dic0321['Regno Unito']

['03-21-2020 00:13',
 '03-21-2020 00:44',
 '03-21-2020 01:14',
 '03-21-2020 01:45',
 '03-21-2020 02:15',
 '03-21-2020 02:45',
 '03-21-2020 03:16',
 '03-21-2020 03:46',
 '03-21-2020 04:17',
 '03-21-2020 04:47',
 '03-21-2020 05:18',
 '03-21-2020 05:48',
 '03-21-2020 06:19',
 '03-21-2020 06:49',
 '03-21-2020 07:19',
 '03-21-2020 07:50',
 '03-21-2020 08:20',
 '03-21-2020 08:51',
 '03-21-2020 09:21',
 '03-21-2020 09:52',
 '03-21-2020 10:22',
 '03-21-2020 10:53',
 '03-21-2020 11:23',
 '03-21-2020 11:54',
 '03-21-2020 12:24',
 '03-21-2020 12:55',
 '03-21-2020 13:25',
 '03-21-2020 13:56',
 '03-21-2020 14:26',
 '03-21-2020 14:57',
 '03-21-2020 15:27',
 '03-21-2020 15:58',
 '03-21-2020 16:28',
 '03-21-2020 16:59',
 '03-21-2020 17:29',
 '03-21-2020 18:00',
 '03-21-2020 18:30',
 '03-21-2020 19:01',
 '03-21-2020 19:32',
 '03-21-2020 20:02',
 '03-21-2020 20:33',
 '03-21-2020 21:03',
 '03-21-2020 21:34',
 '03-21-2020 22:04',
 '03-21-2020 22:34',
 '03-21-2020 23:05',
 '03-21-2020 23:35']

In [35]:
d = datetime.strptime("03-21-2020 04:17", "%m-%d-%Y %H:%M")
dt = d + timedelta(hours=-6)
print(d)
print(dt)

2020-03-21 04:17:00
2020-03-20 22:17:00

In [127]:
def find_timestamp(dt, country_code, c_gmt):
    fuso = c_gmt[str(country_code)]['GMT']
    diff = dt + timedelta(hours=fuso)
    r = diff.apply(datetime.strftime, format = "%m-%d-%Y %H:%M")
    return r

In [128]:
d = [datetime.strptime("03-21-2020 04:17", "%m-%d-%Y %H:%M"),
     datetime.strptime("03-21-2020 10:22", "%m-%d-%Y %H:%M"),
     datetime.strptime("03-21-2020 16:28", "%m-%d-%Y %H:%M"),
     datetime.strptime("03-21-2020 22:34", "%m-%d-%Y %H:%M")] 

times = pd.DataFrame(data=d, columns = ["Regno Unito"])
times #qua inserisco tutti gli orari da estrarre dal dataset in base al paese

          Regno Unito
0 2020-03-21 04:17:00
1 2020-03-21 10:22:00
2 2020-03-21 16:28:00
3 2020-03-21 22:34:00

In [129]:
for c in country: #per ogni paese
    if c != "GB":
        times[country[c]["name"]] = find_timestamp(times["Regno Unito"], c, country)
times["Regno Unito"] = times["Regno Unito"].apply(datetime.strftime, format = "%m-%d-%Y %H:%M")
times

,Regno Unito,USA,India,Germania,Canada,Francia,Corea del sud,Russia,Giappone,Brasile,Messico,Italia
0,03-21-2020 04:17,03-20-2020 23:17,03-21-2020 09:17,03-21-2020 05:17,03-20-2020 23:17,03-21-2020 05:17,03-21-2020 13:17,03-21-2020 07:17,03-21-2020 13:17,03-21-2020 01:17,03-20-2020 22:17,03-21-2020 05:17
1,03-21-2020 10:22,03-21-2020 05:22,03-21-2020 15:22,03-21-2020 11:22,03-21-2020 05:22,03-21-2020 11:22,03-21-2020 19:22,03-21-2020 13:22,03-21-2020 19:22,03-21-2020 07:22,03-21-2020 04:22,03-21-2020 11:22
2,03-21-2020 16:28,03-21-2020 11:28,03-21-2020 21:28,03-21-2020 17:28,03-21-2020 11:28,03-21-2020 17:28,03-22-2020 01:28,03-21-2020 19:28,03-22-2020 01:28,03-21-2020 13:28,03-21-2020 10:28,03-21-2020 17:28
3,03-21-2020 22:34,03-21-2020 17:34,03-22-2020 03:34,03-21-2020 23:34,03-21-2020 17:34,03-21-2020 23:34,03-22-2020 07:34,03-22-2020 01:34,03-22-2020 07:34,03-21-2020 19:34,03-21-2020 16:34,03-21-2020 23:34

ora devo estrarre i dati con questi timestamp "circa" perchè ci possono essere variazioni di pochi minuti

In [149]:
for e in dic0321["Italia"]:
    for t in times["Italia"]:
        if e == t:
            print(e)

03-21-2020 05:17
03-21-2020 11:22
03-21-2020 17:28
03-21-2020 23:34

Ora che ho trovato i timestamp corretti posso estrarre dal json con tutti i 0321 quelli che interessano a noi

In [150]:
path = dir2103 + "\\" 
files = os.listdir(path)

list_videos = []
for file in files:
    if file.endswith(".json") :
        with open(path + file, "r") as read_file:
            j_file = json.load(read_file)
            
        list_videos.extend(j_file)
len(list_videos)

104151

In [169]:
new_2103 = []
for video in list_videos:
    c = video["country_name"]
    for tms in times[c]:
        if video["timestamp"] == tms:
            new_2103.append(video)
            
len(new_2103)

8841

verifico le date corrette

In [167]:
dic0321 = {}
for e in new_2103:
    t = e["timestamp"]
    c = e["country_name"]
    if c not in dic0321.keys(): #se non ho già inserito il country
        dic0321[c] = [t]
    else:
        if t not in dic0321[c] : #se non ho già inserito questa data in quel country
            dic0321[c].append(t)
dic0321

{'USA': ['03-20-2020 23:17',
  '03-21-2020 05:22',
  '03-21-2020 11:28',
  '03-21-2020 17:34'],
 'Regno Unito': ['03-21-2020 04:17',
  '03-21-2020 10:22',
  '03-21-2020 16:28',
  '03-21-2020 22:34'],
 'India': ['03-21-2020 09:17',
  '03-21-2020 15:22',
  '03-21-2020 21:28',
  '03-22-2020 03:34'],
 'Germania': ['03-21-2020 05:17',
  '03-21-2020 11:22',
  '03-21-2020 17:28',
  '03-21-2020 23:34'],
 'Canada': ['03-20-2020 23:17',
  '03-21-2020 05:22',
  '03-21-2020 11:28',
  '03-21-2020 17:34'],
 'Francia': ['03-21-2020 05:17',
  '03-21-2020 11:22',
  '03-21-2020 17:28',
  '03-21-2020 23:34'],
 'Corea del sud': ['03-21-2020 13:17',
  '03-21-2020 19:22',
  '03-22-2020 01:28',
  '03-22-2020 07:34'],
 'Russia': ['03-21-2020 07:17',
  '03-21-2020 13:22',
  '03-21-2020 19:28',
  '03-22-2020 01:34'],
 'Giappone': ['03-21-2020 13:17',
  '03-21-2020 19:22',
  '03-22-2020 01:28',
  '03-22-2020 07:34'],
 'Brasile': ['03-21-2020 01:17',
  '03-21-2020 07:22',
  '03-21-2020 13:28',
  '03-21-2020 19:34'],
 'Messico': ['03-20-2020 22:17',
  '03-21-2020 04:22',
  '03-21-2020 10:28',
  '03-21-2020 16:34'],
 'Italia': ['03-21-2020 05:17',
  '03-21-2020 11:22',
  '03-21-2020 17:28',
  '03-21-2020 23:34']}

dovrebbe essere tutto giusto.

Procedo quindi a salvare su file il json del **21 marzo**

In [170]:
with open('2020.03.21_all_videos.json', 'w') as outfile:
    json.dump(new_2103, outfile)

### 20 marzo
Sistemo il file 20 marzo seguendo il pattern precedente

In [178]:
path = dir2003 + "\\" 
files = os.listdir(path)
vid_2003 = []
for file in files:
    if file.endswith(".json") :
        with open(path + file, "r") as read_file:
            j_file = json.load(read_file)
            
        vid_2003.extend(j_file)

In [180]:
dic0320 = {}
for e in vid_2003:
    t = e["timestamp"]
    c = e["country_name"]
    if c not in dic0320.keys(): #se non ho già inserito il country
        dic0320[c] = [t]
    else:
        if t not in dic0320[c] : #se non ho già inserito questa data in quel country
            dic0320[c].append(t)
dic0320

{'USA': ['03-20-2020 16:11',
  '03-20-2020 16:41',
  '03-20-2020 17:12',
  '03-20-2020 17:42',
  '03-20-2020 18:12',
  '03-20-2020 18:43'],
 'Regno Unito': ['03-20-2020 21:11',
  '03-20-2020 21:41',
  '03-20-2020 22:12',
  '03-20-2020 22:42',
  '03-20-2020 23:12',
  '03-20-2020 23:43'],
 'India': ['03-21-2020 02:11',
  '03-21-2020 02:41',
  '03-21-2020 03:12',
  '03-21-2020 03:42',
  '03-21-2020 04:12',
  '03-21-2020 04:43'],
 'Germania': ['03-20-2020 22:11',
  '03-20-2020 22:41',
  '03-20-2020 23:12',
  '03-20-2020 23:42',
  '03-21-2020 00:12',
  '03-21-2020 00:43'],
 'Canada': ['03-20-2020 16:11',
  '03-20-2020 16:41',
  '03-20-2020 17:12',
  '03-20-2020 17:42',
  '03-20-2020 18:12',
  '03-20-2020 18:43'],
 'Francia': ['03-20-2020 22:11',
  '03-20-2020 22:41',
  '03-20-2020 23:12',
  '03-20-2020 23:42',
  '03-21-2020 00:12',
  '03-21-2020 00:43'],
 'Corea del sud': ['03-21-2020 06:11',
  '03-21-2020 06:41',
  '03-21-2020 07:12',
  '03-21-2020 07:42',
  '03-21-2020 08:12',
  '03-21-2020 08:43'],
 'Russia': ['03-21-2020 00:11',
  '03-21-2020 00:41',
  '03-21-2020 01:12',
  '03-21-2020 01:42',
  '03-21-2020 02:12',
  '03-21-2020 02:43'],
 'Giappone': ['03-21-2020 06:11',
  '03-21-2020 06:41',
  '03-21-2020 07:12',
  '03-21-2020 07:42',
  '03-21-2020 08:12',
  '03-21-2020 08:43'],
 'Brasile': ['03-20-2020 18:11',
  '03-20-2020 18:41',
  '03-20-2020 19:12',
  '03-20-2020 19:42',
  '03-20-2020 20:12',
  '03-20-2020 20:43'],
 'Messico': ['03-20-2020 15:11',
  '03-20-2020 15:41',
  '03-20-2020 16:12',
  '03-20-2020 16:42',
  '03-20-2020 17:12',
  '03-20-2020 17:43'],
 'Italia': ['03-20-2020 22:11',
  '03-20-2020 22:41',
  '03-20-2020 23:12',
  '03-20-2020 23:42',
  '03-21-2020 00:12',
  '03-21-2020 00:43']}

decido di estrarre il "03-20-2020 22:12" Greenwich

In [182]:
d = [datetime.strptime("03-20-2020 22:12", "%m-%d-%Y %H:%M")]
times = pd.DataFrame(data=d, columns = ["Regno Unito"])
times

          Regno Unito
0 2020-03-20 22:12:00

In [183]:
for c in country: #per ogni paese
    if c != "GB":
        times[country[c]["name"]] = find_timestamp(times["Regno Unito"], c, country)
times["Regno Unito"] = times["Regno Unito"].apply(datetime.strftime, format = "%m-%d-%Y %H:%M")
times

,Regno Unito,USA,India,Germania,Canada,Francia,Corea del sud,Russia,Giappone,Brasile,Messico,Italia
0,03-20-2020 22:12,03-20-2020 17:12,03-21-2020 03:12,03-20-2020 23:12,03-20-2020 17:12,03-20-2020 23:12,03-21-2020 07:12,03-21-2020 01:12,03-21-2020 07:12,03-20-2020 19:12,03-20-2020 16:12,03-20-2020 23:12

In [185]:
len(vid_2003)

12658

In [186]:
new_2003 = []
for video in vid_2003:
    c = video["country_name"]
    for tms in times[c]:
        if video["timestamp"] == tms:
            new_2003.append(video)
            
len(new_2003)

2095

verifico di aver estratto quelli giusti

In [187]:
dic0320 = {}
for e in new_2003:
    t = e["timestamp"]
    c = e["country_name"]
    if c not in dic0320.keys(): #se non ho già inserito il country
        dic0320[c] = [t]
    else:
        if t not in dic0320[c] : #se non ho già inserito questa data in quel country
            dic0320[c].append(t)
dic0320

{'USA': ['03-20-2020 17:12'],
 'Regno Unito': ['03-20-2020 22:12'],
 'India': ['03-21-2020 03:12'],
 'Germania': ['03-20-2020 23:12'],
 'Canada': ['03-20-2020 17:12'],
 'Francia': ['03-20-2020 23:12'],
 'Corea del sud': ['03-21-2020 07:12'],
 'Russia': ['03-21-2020 01:12'],
 'Giappone': ['03-21-2020 07:12'],
 'Brasile': ['03-20-2020 19:12'],
 'Messico': ['03-20-2020 16:12'],
 'Italia': ['03-20-2020 23:12']}

carico i dati su file

In [188]:
with open('2020.03.20_all_videos.json', 'w') as outfile:
    json.dump(new_2003, outfile)

### 22 marzo
verifico il 22 marzo e nel caso correggo

In [189]:
path = dir2203 + "\\" 
files = os.listdir(path)
vid_2203 = []
for file in files:
    if file.endswith(".json") :
        with open(path + file, "r") as read_file:
            j_file = json.load(read_file)
            
        vid_2203.extend(j_file)

In [191]:
dic0322 = {}
for e in vid_2203:
    t = e["timestamp"]
    c = e["country_name"]
    if c not in dic0322.keys(): #se non ho già inserito il country
        dic0322[c] = [t]
    else:
        if t not in dic0322[c] : #se non ho già inserito questa data in quel country
            dic0322[c].append(t)
dic0322

{'USA': ['03-22-2020 05:28',
  '03-22-2020 11:28',
  '03-22-2020 17:29',
  '03-21-2020 19:06',
  '03-21-2020 19:36',
  '03-21-2020 20:07',
  '03-21-2020 20:37',
  '03-21-2020 21:07',
  '03-21-2020 21:38',
  '03-21-2020 22:08',
  '03-21-2020 22:39',
  '03-21-2020 23:09',
  '03-21-2020 23:40',
  '03-22-2020 00:10'],
 'Regno Unito': ['03-22-2020 10:28',
  '03-22-2020 16:28',
  '03-22-2020 22:29',
  '03-22-2020 00:06',
  '03-22-2020 00:36',
  '03-22-2020 01:07',
  '03-22-2020 01:37',
  '03-22-2020 02:07',
  '03-22-2020 02:38',
  '03-22-2020 03:08',
  '03-22-2020 03:39',
  '03-22-2020 04:09',
  '03-22-2020 04:40',
  '03-22-2020 05:10'],
 'India': ['03-22-2020 15:28',
  '03-22-2020 21:28',
  '03-23-2020 03:29',
  '03-22-2020 05:06',
  '03-22-2020 05:36',
  '03-22-2020 06:07',
  '03-22-2020 06:37',
  '03-22-2020 07:07',
  '03-22-2020 07:38',
  '03-22-2020 08:08',
  '03-22-2020 08:39',
  '03-22-2020 09:09',
  '03-22-2020 09:40'],
 'Germania': ['03-22-2020 11:28',
  '03-22-2020 17:28',
  '03-22-2020 23:29',
  '03-22-2020 01:06',
  '03-22-2020 01:36',
  '03-22-2020 02:07',
  '03-22-2020 02:37',
  '03-22-2020 03:07',
  '03-22-2020 03:38',
  '03-22-2020 04:08',
  '03-22-2020 04:39',
  '03-22-2020 05:09',
  '03-22-2020 05:40'],
 'Canada': ['03-22-2020 05:28',
  '03-22-2020 11:28',
  '03-22-2020 17:29',
  '03-21-2020 19:06',
  '03-21-2020 19:36',
  '03-21-2020 20:07',
  '03-21-2020 20:37',
  '03-21-2020 21:07',
  '03-21-2020 21:38',
  '03-21-2020 22:08',
  '03-21-2020 22:39',
  '03-21-2020 23:09',
  '03-21-2020 23:40'],
 'Francia': ['03-22-2020 11:28',
  '03-22-2020 17:28',
  '03-22-2020 23:29',
  '03-22-2020 01:06',
  '03-22-2020 01:36',
  '03-22-2020 02:07',
  '03-22-2020 02:37',
  '03-22-2020 03:07',
  '03-22-2020 03:38',
  '03-22-2020 04:08',
  '03-22-2020 04:39',
  '03-22-2020 05:09',
  '03-22-2020 05:40'],
 'Corea del sud': ['03-22-2020 19:28',
  '03-23-2020 01:28',
  '03-23-2020 07:29',
  '03-22-2020 09:06',
  '03-22-2020 09:36',
  '03-22-2020 10:07',
  '03-22-2020 10:37',
  '03-22-2020 11:07',
  '03-22-2020 11:38',
  '03-22-2020 12:08',
  '03-22-2020 12:39',
  '03-22-2020 13:09',
  '03-22-2020 13:40'],
 'Russia': ['03-22-2020 13:28',
  '03-22-2020 19:28',
  '03-23-2020 01:29',
  '03-22-2020 03:06',
  '03-22-2020 03:36',
  '03-22-2020 04:07',
  '03-22-2020 04:37',
  '03-22-2020 05:07',
  '03-22-2020 05:38',
  '03-22-2020 06:08',
  '03-22-2020 06:39',
  '03-22-2020 07:09',
  '03-22-2020 07:40'],
 'Giappone': ['03-22-2020 19:28',
  '03-23-2020 01:28',
  '03-23-2020 07:29',
  '03-22-2020 09:06',
  '03-22-2020 09:36',
  '03-22-2020 10:07',
  '03-22-2020 10:37',
  '03-22-2020 11:07',
  '03-22-2020 11:38',
  '03-22-2020 12:08',
  '03-22-2020 12:39',
  '03-22-2020 13:09',
  '03-22-2020 13:40'],
 'Brasile': ['03-22-2020 07:28',
  '03-22-2020 13:28',
  '03-22-2020 19:29',
  '03-21-2020 21:06',
  '03-21-2020 21:36',
  '03-21-2020 22:07',
  '03-21-2020 22:37',
  '03-21-2020 23:07',
  '03-21-2020 23:38',
  '03-22-2020 00:08',
  '03-22-2020 00:39',
  '03-22-2020 01:09',
  '03-22-2020 01:40'],
 'Messico': ['03-22-2020 04:28',
  '03-22-2020 10:28',
  '03-22-2020 16:29',
  '03-21-2020 18:06',
  '03-21-2020 18:36',
  '03-21-2020 19:07',
  '03-21-2020 19:37',
  '03-21-2020 20:07',
  '03-21-2020 20:38',
  '03-21-2020 21:08',
  '03-21-2020 21:39',
  '03-21-2020 22:09',
  '03-21-2020 22:40'],
 'Italia': ['03-22-2020 11:28',
  '03-22-2020 17:28',
  '03-22-2020 23:29',
  '03-22-2020 01:06',
  '03-22-2020 01:36',
  '03-22-2020 02:07',
  '03-22-2020 02:37',
  '03-22-2020 03:07',
  '03-22-2020 03:38',
  '03-22-2020 04:08',
  '03-22-2020 04:39',
  '03-22-2020 05:09',
  '03-22-2020 05:40']}

direi di tenere le seguenti
- 03-22-2020 10:28
- 03-22-2020 16:28
- 03-22-2020 22:29
- 03-22-2020 04:09

In [192]:
d = [datetime.strptime("03-22-2020 10:28", "%m-%d-%Y %H:%M"),
    datetime.strptime("03-22-2020 16:28", "%m-%d-%Y %H:%M"),
    datetime.strptime("03-22-2020 22:29", "%m-%d-%Y %H:%M"),
    datetime.strptime("03-22-2020 04:09", "%m-%d-%Y %H:%M"),]
times = pd.DataFrame(data=d, columns = ["Regno Unito"])
times

          Regno Unito
0 2020-03-22 10:28:00
1 2020-03-22 16:28:00
2 2020-03-22 22:29:00
3 2020-03-22 04:09:00

In [193]:
for c in country: #per ogni paese
    if c != "GB":
        times[country[c]["name"]] = find_timestamp(times["Regno Unito"], c, country)
times["Regno Unito"] = times["Regno Unito"].apply(datetime.strftime, format = "%m-%d-%Y %H:%M")
times

,Regno Unito,USA,India,Germania,Canada,Francia,Corea del sud,Russia,Giappone,Brasile,Messico,Italia
0,03-22-2020 10:28,03-22-2020 05:28,03-22-2020 15:28,03-22-2020 11:28,03-22-2020 05:28,03-22-2020 11:28,03-22-2020 19:28,03-22-2020 13:28,03-22-2020 19:28,03-22-2020 07:28,03-22-2020 04:28,03-22-2020 11:28
1,03-22-2020 16:28,03-22-2020 11:28,03-22-2020 21:28,03-22-2020 17:28,03-22-2020 11:28,03-22-2020 17:28,03-23-2020 01:28,03-22-2020 19:28,03-23-2020 01:28,03-22-2020 13:28,03-22-2020 10:28,03-22-2020 17:28
2,03-22-2020 22:29,03-22-2020 17:29,03-23-2020 03:29,03-22-2020 23:29,03-22-2020 17:29,03-22-2020 23:29,03-23-2020 07:29,03-23-2020 01:29,03-23-2020 07:29,03-22-2020 19:29,03-22-2020 16:29,03-22-2020 23:29
3,03-22-2020 04:09,03-21-2020 23:09,03-22-2020 09:09,03-22-2020 05:09,03-21-2020 23:09,03-22-2020 05:09,03-22-2020 13:09,03-22-2020 07:09,03-22-2020 13:09,03-22-2020 01:09,03-21-2020 22:09,03-22-2020 05:09

In [194]:
len(vid_2203)

28184

In [195]:
new_2203 = []
for video in vid_2203:
    c = video["country_name"]
    for tms in times[c]:
        if video["timestamp"] == tms:
            new_2203.append(video)
            
len(new_2203)

8920

verifico di aver estratto quelli corretti

In [196]:
dic0322 = {}
for e in new_2203:
    t = e["timestamp"]
    c = e["country_name"]
    if c not in dic0322.keys(): #se non ho già inserito il country
        dic0322[c] = [t]
    else:
        if t not in dic0322[c] : #se non ho già inserito questa data in quel country
            dic0322[c].append(t)
dic0322

{'USA': ['03-22-2020 05:28',
  '03-22-2020 11:28',
  '03-22-2020 17:29',
  '03-21-2020 23:09'],
 'Regno Unito': ['03-22-2020 10:28',
  '03-22-2020 16:28',
  '03-22-2020 22:29',
  '03-22-2020 04:09'],
 'India': ['03-22-2020 15:28',
  '03-22-2020 21:28',
  '03-23-2020 03:29',
  '03-22-2020 09:09'],
 'Germania': ['03-22-2020 11:28',
  '03-22-2020 17:28',
  '03-22-2020 23:29',
  '03-22-2020 05:09'],
 'Canada': ['03-22-2020 05:28',
  '03-22-2020 11:28',
  '03-22-2020 17:29',
  '03-21-2020 23:09'],
 'Francia': ['03-22-2020 11:28',
  '03-22-2020 17:28',
  '03-22-2020 23:29',
  '03-22-2020 05:09'],
 'Corea del sud': ['03-22-2020 19:28',
  '03-23-2020 01:28',
  '03-23-2020 07:29',
  '03-22-2020 13:09'],
 'Russia': ['03-22-2020 13:28',
  '03-22-2020 19:28',
  '03-23-2020 01:29',
  '03-22-2020 07:09'],
 'Giappone': ['03-22-2020 19:28',
  '03-23-2020 01:28',
  '03-23-2020 07:29',
  '03-22-2020 13:09'],
 'Brasile': ['03-22-2020 07:28',
  '03-22-2020 13:28',
  '03-22-2020 19:29',
  '03-22-2020 01:09'],
 'Messico': ['03-22-2020 04:28',
  '03-22-2020 10:28',
  '03-22-2020 16:29',
  '03-21-2020 22:09'],
 'Italia': ['03-22-2020 11:28',
  '03-22-2020 17:28',
  '03-22-2020 23:29',
  '03-22-2020 05:09']}

carico ora su file

In [197]:
with open('2020.03.22_all_videos.json', 'w') as outfile:
    json.dump(new_2203, outfile)